### ISSUE TITLE
Issues on Xiaomi SDM439

### ISSUE THREAD

**Issue by me-cafebabe** [Mi-Thorium/kernel_msm-4.19#5]
- [x] Random reboot
- [x] Volume Up button
- [x] IR
- [x] In-call audio

Display related:
- [x] FB blank/unblank
- [x] Power-off becomes restart

Unsure:
- [ ] Thermal (?)
- [x] on olive, speaker volume is much lower

**Comment by me-cafebabe** [comment]
dmesg of in-call audio issue:

pine:
[  107.154313] aw87329_hw_off enter
[  107.192207] afe_close: port_id = 0x1000
[  107.222499] __afe_port_start: port id: 0x1000
[  107.222515] afe_find_cal_topo_id_by_port: port id: 0x1000, dev_acdb_id: 7
[  107.222520] afe_find_cal_topo_id_by_port: top_id:112fc acdb_id:7 afe_port_id:0x1000
[  107.222524] afe_get_cal_topology_id: port_id = 0x1000 acdb_id = 7 topology_id = 0x112fc cal_type_index=8 ret=0
[  107.222831] afe_send_port_topology_id: AFE set topology id 0x112fc  enable for port 0x1000 ret 0
[  107.222836] send_afe_cal_type: cal_index is 0
[  107.222839] send_afe_cal_type: dev_acdb_id[40] is 7
[  107.222842] afe_find_cal: cal_index 0 port_id 0x1000 port_index 40
[  107.222846] afe_find_cal: acdb_id 7 dev_acdb_id 7 sample_rate 48000 afe_sample_rates 48000
[  107.222849] afe_find_cal: cal block is a match, size is 0
[  107.222852] send_afe_cal_type: Sending cal_index cal 0
[  107.222855] send_afe_cal_type: No cal sent for cal_index 0, port_id = 0x1000! ret -22
[  107.223127] afe_send_hw_delay: port_id 0x1000 rate 48000 delay_usec 474 status 0
[  107.705973] __afe_port_start: port id: 0x1005
[  107.705994] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[  107.705996] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[  107.705999] afe_find_cal_topo_id_by_port: top_id:112fb acdb_id:41 afe_port:0x1005
[  107.706001] afe_get_cal_topology_id: port_id = 0x1005 acdb_id = 41 topology_id = 0x112fb cal_type_index=8 ret=0
[  107.706127] afe_send_port_topology_id: AFE set topology id 0x112fb  enable for port 0x1005 ret 0
[  107.706132] send_afe_cal_type: cal_index is 1
[  107.706134] send_afe_cal_type: dev_acdb_id[39] is 0
[  107.706136] send_afe_cal_type: Sending cal_index cal 1
[  107.706138] send_afe_cal_type: No cal sent for cal_index 1, port_id = 0x1005! ret -22
[  107.706244] afe_send_hw_delay: port_id 0x1005 rate 48000 delay_usec 578 status 0
[  107.770209] qdsp_cvp_callback: cmd = 0x1133d returned error = 0x2
[  107.770318] voice_send_cvp_channel_info_v2: DSP returned error[ADSP_EBADPARAM] handle = 256
[  107.770329] voice_send_cvp_channel_info_cmd: Error in sending cvp_channel_info RX: -22
[  107.770335] voice_send_cvp_media_fmt_info_cmd: Set channel info failed err: -22
[  107.770341] voice_setup_vocproc: Set media format info failed err:-22
[  107.770346] setup voice failed

olive:
[   44.155334] aw87519_hw_off enter
[   44.166457] binder: 971:1240 ioctl 40046210 7abac0b490 returned -22
[   44.192987] afe_close: port_id = 0x1000
[   44.238549] __afe_port_start: port id: 0x1000
[   44.238578] afe_find_cal_topo_id_by_port: port id: 0x1000, dev_acdb_id: 7
[   44.238582] afe_find_cal_topo_id_by_port: top_id:112fc acdb_id:7 afe_port_id:0x1000
[   44.238585] afe_get_cal_topology_id: port_id = 0x1000 acdb_id = 7 topology_id = 0x112fc cal_type_index=8 ret=0
[   44.238744] afe_send_port_topology_id: AFE set topology id 0x112fc  enable for port 0x1000 ret 0
[   44.238747] send_afe_cal_type: cal_index is 0
[   44.238749] send_afe_cal_type: dev_acdb_id[40] is 7
[   44.238752] afe_find_cal: cal_index 0 port_id 0x1000 port_index 40
[   44.238755] afe_find_cal: acdb_id 7 dev_acdb_id 7 sample_rate 48000 afe_sample_rates 48000
[   44.238758] afe_find_cal: cal block is a match, size is 0
[   44.238760] send_afe_cal_type: Sending cal_index cal 0
[   44.238764] send_afe_cal_type: No cal sent for cal_index 0, port_id = 0x1000! ret -22
[   44.238907] afe_send_hw_delay: port_id 0x1000 rate 48000 delay_usec 474 status 0
[   44.346533] __afe_port_start: port id: 0x1005
[   44.346554] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[   44.346558] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[   44.346561] afe_find_cal_topo_id_by_port: top_id:112fb acdb_id:41 afe_port:0x1005
[   44.346565] afe_get_cal_topology_id: port_id = 0x1005 acdb_id = 41 topology_id = 0x112fb cal_type_index=8 ret=0
[   44.346880] afe_send_port_topology_id: AFE set topology id 0x112fb  enable for port 0x1005 ret 0
[   44.346888] send_afe_cal_type: cal_index is 1
[   44.346892] send_afe_cal_type: dev_acdb_id[39] is 0
[   44.346894] send_afe_cal_type: Sending cal_index cal 1
[   44.346897] send_afe_cal_type: No cal sent for cal_index 1, port_id = 0x1005! ret -22
[   44.347722] afe_send_hw_delay: port_id 0x1005 rate 48000 delay_usec 578 status 0
[   44.414072] qdsp_cvp_callback: cmd = 0x1133d returned error = 0x2
[   44.414110] voice_send_cvp_channel_info_v2: DSP returned error[ADSP_EBADPARAM] handle = 256
[   44.414118] voice_send_cvp_channel_info_cmd: Error in sending cvp_channel_info RX: -22
[   44.414124] voice_send_cvp_media_fmt_info_cmd: Set channel info failed err: -22
[   44.414130] voice_setup_vocproc: Set media format info failed err:-22
[   44.414134] setup voice failed

**Comment by me-cafebabe** [comment]
[    4.829424] gpio-keys soc:gpio_keys: Found button without gpio or irq
[    4.829443] gpio-keys: probe of soc:gpio_keys failed with error -22

**Comment by me-cafebabe** [comment]
mdss-pll.c:234:         if (strstr(mdss_mdp_panel, "mdss_dsi_ili9881d_hdplus_video_c3e")) {
mdss-pll.c:235:                 pr_info("%s: Disable ssc_en for mdss_dsi_ili9881d_hdplus_video_c3e panel\n", __func__);

does not work at all

maybe the same for novatek??

**Comment by Jobatphysics** [comment]
> mdss-pll.c:234: if (strstr(mdss_mdp_panel, "mdss_dsi_ili9881d_hdplus_video_c3e")) { mdss-pll.c:235: pr_info("%s: Disable ssc_en for mdss_dsi_ili9881d_hdplus_video_c3e panel\n", **func**);
> 
> does not work at all
> 
> maybe the same for novatek??

I found these drivers for our displays as they are working fine on 4.14.xxx so maybe this can help https://github.com/BeastRoms-Devices/kernel_realme_RMX1927/tree/master/drivers/input/touchscreen

**Comment by me-cafebabe** [comment]
k4.9 dmesg of in-call audio:

[   58.479938] aw87519_hw_off enter
[   58.561936] __afe_port_start: port id: 0x1000
[   58.561954] afe_find_cal_topo_id_by_port: port id: 0x1000, dev_acdb_id: 7
[   58.561959] afe_find_cal_topo_id_by_port: top_id:112fc acdb_id:7 afe_port_id:0x1000
[   58.561965] afe_get_cal_topology_id: port_id = 0x1000 acdb_id = 7 topology_id = 0x112fc cal_type_index=8 ret=0
[   58.562256] afe_send_port_topology_id: AFE set topology id 0x112fc  enable for port 0x1000 ret 0
[   58.562261] send_afe_cal_type: cal_index is 0
[   58.562265] send_afe_cal_type: dev_acdb_id[40] is 7
[   58.562270] afe_find_cal: cal_index 0 port_id 0x1000 port_index 40
[   58.562276] afe_find_cal: acdb_id 7 dev_acdb_id 7 sample_rate 48000 afe_sample_rates 48000
[   58.562279] afe_find_cal: cal block is a match, size is 0
[   58.562283] send_afe_cal_type: Sending cal_index cal 0
[   58.562287] send_afe_cal_type: No cal sent for cal_index 0, port_id = 0x1000! ret -22
[   58.562596] afe_send_hw_delay: port_id 0x1000 rate 48000 delay_usec 474 status 0
[   58.936253] __afe_port_start: port id: 0x1005
[   58.936268] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[   58.936271] afe_find_cal_topo_id_by_port: port id: 0x1005, dev_acdb_id: 0
[   58.936274] afe_find_cal_topo_id_by_port: top_id:112fb acdb_id:41 afe_port:0x1005
[   58.936276] afe_get_cal_topology_id: port_id = 0x1005 acdb_id = 41 topology_id = 0x112fb cal_type_index=8 ret=0
[   58.936679] afe_send_port_topology_id: AFE set topology id 0x112fb  enable for port 0x1005 ret 0
[   58.936692] send_afe_cal_type: cal_index is 1
[   58.936695] send_afe_cal_type: dev_acdb_id[39] is 0
[   58.936699] send_afe_cal_type: Sending cal_index cal 1
[   58.936702] send_afe_cal_type: No cal sent for cal_index 1, port_id = 0x1005! ret -22
[   58.936715] send_afe_cal_type: cal_index is 2
[   58.936717] send_afe_cal_type: dev_acdb_id[39] is 0
[   58.936719] send_afe_cal_type: Sending cal_index cal 2
[   58.936721] send_afe_cal_type: No cal sent for cal_index 2, port_id = 0x1005! ret -22
[   58.936956] afe_send_hw_delay: port_id 0x1005 rate 48000 delay_usec 578 status 0
[   59.037175] qdsp_cvp_callback: cmd = 0x112c2 returned error = 0x9
[   59.037222] voice_send_vol_step_cmd: DSP returned error[ADSP_EALREADY]

**Comment by me-cafebabe** [comment]
[   11.049727] apr_tal_rpmsg soc:smd:adsp.apr_audio_svc.-1.-1: apr_tal_rpmsg_probe: Channel[apr_audio_svc] state[Up]
[   14.137857] apr_tal_rpmsg_probe no parent source pid found
[   14.137875] apr_tal_rpmsg soc:smd:modem.apr_audio_svc.-1.-1: rpmsg_dev_probe: failed: -22
[   14.137914] apr_tal_rpmsg: probe of soc:smd:modem.apr_audio_svc.-1.-1 failed with error -22

**Comment by me-cafebabe** [comment]
[   14.158469] memshare_child soc:qcom,memshare:qcom,client_3: memshare: hyp_assign_phys failed size=5242880 err=-99
[   14.158475] memshare_child soc:qcom,memshare:qcom,client_3: memshare_alloc: client_id: 1, alloc_resp.num_bytes: 5242880, alloc_resp.resp.result: 0
[   14.161539] apr_tal_rpmsg_audio soc:smd:modem.apr_audio_svc.-1.-1: apr_tal_rpmsg_probe: Channel[apr_audio_svc] state[Up]
